apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: rancher-crictl
  name: rancher-crictl
spec:
  selector:
    matchLabels:
      name: rancher-crictl
  template:
    metadata:
      labels:
        name: rancher-crictl
    spec:
      volumes:
        - name: cri-sock
          hostPath:
            path: "/run/containerd/containerd.sock"
      containers:
        - name: rancher-crictl
          image: rancher/crictl:v1.19.0
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do crictl images ls; done;" ]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /run/containerd/containerd.sock
              name: cri-sock
              readOnly: false
